services:
  - type: web
    name: mcp-brave-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BRAVE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 